export const images = {
	logo: '/assets/images/logo.png',
	gitLogo: '/assets/images/git-logo.png',
	navigation: {
		homeInactive: '/assets/images/ic-home-inactive.png',
		homeActive: '/assets/images/ic-home-active.png',
		profileInactive: '/assets/images/ic-profile-inactive.png',
		profileActive: '/assets/images/ic-profile-active.png',
		searchInactive: '/assets/images/ic-search-inactive.png',
		searchActive: '/assets/images/ic-search-active.png',
		communityInactive: '/assets/images/ic-community-inactive.png',
		communityActive: '/assets/images/ic-community-active.png',
	},
	header: {
		back: '/assets/images/ic-arrow-back.png',
	},
	arrowLeft: '/assets/images/ic-arrow-left.png',
	arrowRight: '/assets/images/ic-arrow-right.png',
	arrowDown: '/assets/images/ic-arrow-down.png',
	arrowUp: '/assets/images/ic-arrow-up.png',
	alarm: '/assets/images/ic-alarm.png',
	calendar: '/assets/images/ic-calendar.png',
	chat: '/assets/images/ic-chat.png',
	gitMessage: '/assets/images/ic-gm.png',
	like: '/assets/images/ic-like.png',
	share: '/assets/images/ic-share.png',
	userMark: '/assets/images/ic-user-mark.png',
	menu: '/assets/images/ic-menu.png',
	close: '/assets/images/ic-close.png',
	dummy: {
		dummy1: '/assets/images/dummy1.png',
		dummy2: '/assets/images/dummy2.png',
	},
};
